import type { Metadata } from "next";
import { Inter, Do_Hyeon } from "next/font/google";

import "./globals.css";
import Frame from "@/components/frame";
import { getNowDate } from "@/functions";
import Link from "next/link";
import Navigation from "@/components/navigation";
import { Header } from "@/components/layout/header";

const inter = Inter({ subsets: ["latin"] });
const doHyeon = Do_Hyeon({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const { year, month, day, dateString } = getNowDate();
    return (
        <html lang="ko" className="bg-sub">
            <body className={doHyeon.className}>
                <div className="w-screen min-h-screen overflow-hidden text-point break-keep">
                    <Header />
                    <div className="mt-16">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
